# Generated by Django 3.1.7 on 2021-06-11 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210610_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed', models.PositiveIntegerField(default=0)),
                ('words', models.PositiveIntegerField(default=0)),
                ('touch', models.PositiveIntegerField(default=0)),
                ('acts', models.PositiveIntegerField(default=0)),
                ('gifts', models.PositiveIntegerField(default=0)),
                ('quality_time', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(default='user_deleted', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='statistics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
