# Generated by Django 3.1.7 on 2021-06-11 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210611_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='touch',
            field=models.PositiveIntegerField(default=0, verbose_name='physical Touch'),
        ),
    ]
