# Generated by Django 3.1.7 on 2021-06-11 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210611_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='acts',
            field=models.PositiveIntegerField(default=0, verbose_name='acts of Service'),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='gifts',
            field=models.PositiveIntegerField(default=0, verbose_name='receiving Gifts'),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='quality_time',
            field=models.PositiveIntegerField(default=0, verbose_name='quality Time'),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='words',
            field=models.PositiveIntegerField(default=0, verbose_name='words of Affirmation'),
        ),
    ]
