# Generated by Django 3.1.7 on 2021-06-15 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210611_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='acts',
            field=models.PositiveIntegerField(default=0, verbose_name='Acts of Service'),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='gifts',
            field=models.PositiveIntegerField(default=0, verbose_name='Receiving Gifts'),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='quality_time',
            field=models.PositiveIntegerField(default=0, verbose_name='Quality Time'),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='touch',
            field=models.PositiveIntegerField(default=0, verbose_name='Physical Touch'),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='words',
            field=models.PositiveIntegerField(default=0, verbose_name='Words of Affirmation'),
        ),
    ]
