# Generated by Django 3.1.7 on 2021-09-23 17:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20210923_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(default='c4fb615952e8e7bffa6b38fb173388ab28c13211ec6a59232357bcb2a6735684', max_length=64)),
                ('activated_at', models.DateTimeField(default=None, null=True)),
                ('expires_at', models.DateTimeField(default=datetime.datetime(2021, 9, 23, 17, 55, 40, 812113, tzinfo=utc))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
