# Generated by Django 3.1.7 on 2021-09-23 19:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_activation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 23, 19, 48, 58, 915031, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='activation',
            name='token',
            field=models.CharField(default='401f5eda3ba3ce8286c504b05fcc7be95ef19b4a6c7173d30b4fb8d3c182d1ab', max_length=64),
        ),
    ]
