# Generated by Django 3.1.7 on 2021-06-06 21:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('needs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userneedpending',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userneedmodel',
            name='need',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='needs.needtemplatemodel'),
        ),
        migrations.AddField(
            model_name='userneedmodel',
            name='pending_list',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='needs.userneedpending'),
        ),
        migrations.AddField(
            model_name='userneedmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='needs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='needtemplatemodel',
            name='category',
            field=models.ManyToManyField(to='needs.CategoryModel'),
        ),
        migrations.AddField(
            model_name='needtemplatemodel',
            name='need',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='needs.needmodel'),
        ),
        migrations.AddField(
            model_name='needtemplatemodel',
            name='tag',
            field=models.ManyToManyField(to='needs.TagModel'),
        ),
    ]
