# Generated by Django 3.1.7 on 2021-05-03 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('needs', '0002_auto_20210503_2049'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='CategoryModel',
        ),
        migrations.RenameModel(
            old_name='NeedCategory',
            new_name='NeedCategoryModel',
        ),
    ]
