# Generated by Django 3.1.7 on 2021-06-09 20:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('needs', '0003_auto_20210607_0106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userneedmodel',
            name='scale',
        ),
        migrations.AddField(
            model_name='userneedmodel',
            name='confirmed_with',
            field=models.ManyToManyField(blank=True, related_name='friends_confirmed', to=settings.AUTH_USER_MODEL),
        ),
    ]
