# Generated by Django 3.1.7 on 2021-05-05 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('needs', '0003_auto_20210504_0127'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NeedTag',
            new_name='NeedTagModel',
        ),
        migrations.RenameModel(
            old_name='Tag',
            new_name='TagModel',
        ),
    ]
