# Generated by Django 3.1.7 on 2021-06-09 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('needs', '0004_auto_20210609_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userneedmodel',
            name='pending_request',
        ),
        migrations.AddField(
            model_name='userneedmodel',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
