# Generated by Django 3.1.7 on 2021-05-05 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('needs', '0006_auto_20210505_1840'),
    ]

    operations = [
        migrations.RenameField(
            model_name='needmodel',
            old_name='active',
            new_name='is_active',
        ),
    ]
